---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)

N <- 24
deviant_simple_mean <- (85.9 / 31.59) * 500
deviant_unusual_mean <- (181.44 / 31.59) * 500
deviant_mixed_mean <- (98.88 / 31.59) * 500

deviant_simple_sem <- (9.92 / 31.59) * 500
deviant_unusual_sem <- (26.1 / 31.59) * 500
deviant_mixed_sem <- (15.6 / 31.59) * 500

deviant_simple_sd <- deviant_simple_sem * sqrt(N)
deviant_unusual_sd <- deviant_unusual_sem * sqrt(N)
deviant_mixed_sd <- deviant_mixed_sem * sqrt(N)

bkgd_simple_mean <- (48.02 / 31.59) * 500
bkgd_unusual_mean <- (53.6 / 31.59) * 500
bkgd_mixed_mean <- (58.53 / 31.59) * 500

bkgd_simple_sem <- (10.52 / 31.59) * 500
bkgd_unusual_sem <- (4.27 / 31.59) * 500
bkgd_mixed_sem <- (16.94 / 31.59) * 500

bkgd_simple_sd <- bkgd_simple_sem * sqrt(N)
bkgd_unusual_sd <- bkgd_unusual_sem * sqrt(N)
bkgd_mixed_sd <- bkgd_mixed_sem * sqrt(N)

```

# Generate artificial data 
```{r}
simulate_data <- function(sample_size, 
                          deviant_simple_mu, deviant_simple_sd,
                          deviant_unusual_mu, deviant_unusual_sd,
                          deviant_mixed_mu, deviant_mixed_sd,
                          bkgd_simple_mu, bkgd_simple_sd,
                          bkgd_unusual_mu, bkgd_unusual_sd,
                          bkgd_mixed_mu, bkgd_mixed_sd){
  
  deviant_simple <- rnorm(sample_size, deviant_simple_mu, deviant_simple_sd)
  deviant_unusual <- rnorm(sample_size,deviant_unusual_mu, deviant_unusual_sd)
  deviant_mixed <- rnorm(sample_size,deviant_mixed_mu, deviant_mixed_sd)
  
  bkgd_simple <- rnorm(sample_size,bkgd_simple_mu, bkgd_simple_sd)
  bkgd_unusual <- rnorm(sample_size,bkgd_unusual_mu, bkgd_unusual_sd)
  bkgd_mixed <- rnorm(sample_size,bkgd_mixed_mu, bkgd_mixed_sd)
  
  return(data.frame(
    deviant_simple = deviant_simple,
    deviant_unusual = deviant_unusual,
    deviant_mixed = deviant_mixed,
    bkgd_simple = bkgd_simple, 
    bkgd_unusual = bkgd_unusual, 
    bkgd_mixed = bkgd_mixed
  ))

}

# simulate_data(24,
#               deviant_simple_mean, deviant_simple_sd,
#               deviant_unusual_mean, deviant_unusual_sd,
#               deviant_mixed_mean, deviant_mixed_sd,
#               bkgd_simple_mean, bkgd_simple_sd,
#               bkgd_unusual_mean, bkgd_unusual_sd,
#               bkgd_mixed_mean, bkgd_mixed_sd)


data <- simulate_data(24,
              deviant_simple_mean, deviant_simple_sem,
              deviant_unusual_mean, deviant_unusual_sem,
              deviant_mixed_mean, deviant_mixed_sem,
              bkgd_simple_mean, bkgd_simple_sem,
              bkgd_unusual_mean, bkgd_unusual_sem,
              bkgd_mixed_mean, bkgd_mixed_sem)

data
```


```{r}
data$subject <- seq_len(nrow(data))
tidy_data <- data %>% 
  pivot_longer(cols = deviant_simple:bkgd_mixed,
               names_to = "trial_info",
               values_to = "trial_looking_time") %>% 
  mutate(
    block = case_when(
      grepl("simple", trial_info) ~ "simple",
      grepl("unusual", trial_info) ~ "unusual", 
      grepl("mixed", trial_info) ~ "mixed"
    ),
    trial_stimulus_type = case_when(
      grepl("deviant", trial_info) ~ "deviant", 
      grepl("bkgd", trial_info) ~ "background"
    )
  ) %>% 
  select(-trial_info)

tidy_data
```

```{r}
lm_res <- lmer(log(trial_looking_time) ~ trial_stimulus_type * block + (1|subject), 
     data = tidy_data)

View(lm_res)
```


#function for analysis
```{r}
# get the interaction effect p value
run_anova <- function(data){
  
  anova_res <- anova_test(data = data, 
           formula = trial_looking_time ~ trial_stimulus_type * block,
           within = c(trial_stimulus_type,block),
           dv = trial_looking_time)
  # get the p val for the interaction term 
  return(anova_res$p[nrow(anova_res)])
  
}

run_lme <- function(data){
  
  lm_res <- lmer(log(trial_looking_time) ~ trial_stimulus_type * block + (1|subject), 
     data = data)
}

```

































